/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    AttendanceAnalytics: typeof import('./src/components/hrss/AttendanceAnalytics.vue')['default']
    AttendanceFilters: typeof import('./src/components/hrss/attendance/AttendanceFilters.vue')['default']
    AttendanceHeatmap: typeof import('./src/components/hrss/AttendanceHeatmap.vue')['default']
    AttendanceTable: typeof import('./src/components/hrss/attendance/AttendanceTable.vue')['default']
    AttendanceToolbar: typeof import('./src/components/hrss/attendance/AttendanceToolbar.vue')['default']
    EditAttendanceDialog: typeof import('./src/components/hrss/attendance/EditAttendanceDialog.vue')['default']
    EmployeeCard: typeof import('./src/components/hrss/EmployeeCard.vue')['default']
    ImportAttendanceDialog: typeof import('./src/components/hrss/attendance/ImportAttendanceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftAssignmentBulk: typeof import('./src/components/hrss/shift/ShiftAssignmentBulk.vue')['default']
    ShiftAssignmentForm: typeof import('./src/components/hrss/shift/ShiftAssignmentForm.vue')['default']
    ShiftAssignmentTable: typeof import('./src/components/hrss/shift/ShiftAssignmentTable.vue')['default']
    ShiftTemplateForm: typeof import('./src/components/hrss/shift/ShiftTemplateForm.vue')['default']
    ShiftTemplates: typeof import('./src/components/hrss/shift/ShiftTemplates.vue')['default']
    TimeField: typeof import('./src/components/common/TimeField.vue')['default']
    WorkCalendarDialog: typeof import('./src/components/hrss/WorkCalendarDialog.vue')['default']
  }
}
