// backend/models/ta/Roadmap.js

const mongoose = require('mongoose');

const roadmapSchema = new mongoose.Schema(
  {
    year: {
      type: Number,
      required: true,
    },

    month: {
      type: String,
      required: true, // Jan, Feb, Mar...
      trim: true,
    },

    type: {
      type: String,
      enum: ['White Collar', 'Blue Collar'],
      required: true,
    },

    subType: {
      type: String,
      enum: ['Sewer', 'Non-Sewer', null],
      default: null,
    },

    // ✅ Manual/Planned HC only.
    // Blue Collar: HR/Admin can input roadmapHC manually.
    // White Collar: generated automatically from requisitions.
    roadmapHC: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },

    // ✅ Do NOT store manual actualHC anymore.
    // actualHC is calculated in controller from Candidate old + new data.

    // ✅ Do NOT store manual hiringTargetHC anymore.
    // hiringTargetHC = roadmapHC - actualHC, calculated in controller.

    company: {
      type: String,
      required: true,
      uppercase: true,
      trim: true,
    },

    // MANUAL = Blue Collar roadmap input by HR/Admin
    // JOB_REQUISITION = White Collar roadmap generated from requisition targetCandidates
    // SYSTEM = generated by system sync
    generatedFrom: {
      type: String,
      enum: ['MANUAL', 'JOB_REQUISITION', 'SYSTEM'],
      default: 'MANUAL',
    },
  },
  { timestamps: true }
);

roadmapSchema.pre('validate', function normalizeRoadmap(next) {
  if (this.company) {
    this.company = String(this.company).trim().toUpperCase();
  }

  if (this.month) {
    this.month = String(this.month).trim();
  }

  if (this.type === 'White Collar') {
    this.subType = null;
  }

  if (this.type === 'Blue Collar' && !this.subType) {
    this.subType = 'Non-Sewer';
  }

  this.roadmapHC = Math.max(0, Number(this.roadmapHC || 0));

  next();
});

roadmapSchema.index(
  {
    company: 1,
    year: 1,
    month: 1,
    type: 1,
    subType: 1,
  },
  { unique: true }
);

module.exports = mongoose.model('Roadmap', roadmapSchema);